export const F1_TEAMS = [
  {
    id: "mclaren",
    name: "McLaren",
    color: "#FF8700",
    secondaryColor: "#0090FF",
    logo: "/images/teams/mclaren.png",
  },
  {
    id: "ferrari",
    name: "Ferrari",
    color: "#DC0000",
    secondaryColor: "#FFFF00",
    logo: "/images/teams/ferrari.png",
  },
  {
    id: "redbull",
    name: "Red Bull Racing",
    color: "#0600EF",
    secondaryColor: "#FF0000",
    logo: "/images/teams/redbull.png",
  },
  {
    id: "mercedes",
    name: "Mercedes",
    color: "#00D2BE",
    secondaryColor: "#000000",
    logo: "/images/teams/mercedes.png",
  },
  {
    id: "williams",
    name: "Williams",
    color: "#005AFF",
    secondaryColor: "#FFFFFF",
    logo: "/images/teams/williams.png",
  },
  {
    id: "alpine",
    name: "Alpine",
    color: "#0090FF",
    secondaryColor: "#FF0000",
    logo: "/images/teams/alpine.png",
  },
  {
    id: "astonmartin",
    name: "Aston Martin",
    color: "#006F62",
    secondaryColor: "#FFFFFF",
    logo: "/images/teams/astonmartin.png",
  },
  {
    id: "racingbulls",
    name: "Racing Bulls",
    color: "#0032FF",
    secondaryColor: "#FF0000",
    logo: "/images/teams/rb.png",
  },
  {
    id: "haas",
    name: "Haas F1 Team",
    color: "#1B1E23",
    secondaryColor: "#FF0000",
    logo: "/images/teams/haas.png",
  },
  {
    id: "sauber",
    name: "Sauber",
    color: "#00FF00",
    secondaryColor: "#000000",
    logo: "/images/teams/sauber.png",
  },
]

export const F1_DRIVERS = [
  {
    id: "norris",
    name: "Lando Norris",
    team: "McLaren",
    teamId: "mclaren",
  },
  {
    id: "piastri",
    name: "Oscar Piastri",
    team: "McLaren",
    teamId: "mclaren",
  },
  {
    id: "leclerc",
    name: "Charles Leclerc",
    team: "Ferrari",
    teamId: "ferrari",
  },
  {
    id: "hamilton",
    name: "Lewis Hamilton",
    team: "Ferrari",
    teamId: "ferrari",
  },
  {
    id: "verstappen",
    name: "Max Verstappen",
    team: "Red Bull Racing",
    teamId: "redbull",
  },
  {
    id: "tsunoda",
    name: "Yuki Tsunoda",
    team: "Red Bull Racing",
    teamId: "redbull",
  },
  {
    id: "russell",
    name: "George Russell",
    team: "Mercedes",
    teamId: "mercedes",
  },
  {
    id: "antonelli",
    name: "Kimi Antonelli",
    team: "Mercedes",
    teamId: "mercedes",
  },
  {
    id: "albon",
    name: "Alexander Albon",
    team: "Williams",
    teamId: "williams",
  },
  {
    id: "sainz",
    name: "Carlos Sainz",
    team: "Williams",
    teamId: "williams",
  },
  {
    id: "gasly",
    name: "Pierre Gasly",
    team: "Alpine",
    teamId: "alpine",
  },
  {
    id: "colapinto",
    name: "Franco Colapinto",
    team: "Alpine",
    teamId: "alpine",
  },
  {
    id: "alonso",
    name: "Fernando Alonso",
    team: "Aston Martin",
    teamId: "astonmartin",
  },
  {
    id: "stroll",
    name: "Lance Stroll",
    team: "Aston Martin",
    teamId: "astonmartin",
  },
  {
    id: "lawson",
    name: "Liam Lawson",
    team: "Racing Bulls",
    teamId: "racingbulls",
  },
  {
    id: "hadjar",
    name: "Isack Hadjar",
    team: "Racing Bulls",
    teamId: "racingbulls",
  },
  {
    id: "ocon",
    name: "Esteban Ocon",
    team: "Haas F1 Team",
    teamId: "haas",
  },
  {
    id: "bearman",
    name: "Oliver Bearman",
    team: "Haas F1 Team",
    teamId: "haas",
  },
  {
    id: "hulkenberg",
    name: "Nico Hülkenberg",
    team: "Sauber",
    teamId: "sauber",
  },
  {
    id: "bortoleto",
    name: "Gabriel Bortoleto",
    team: "Sauber",
    teamId: "sauber",
  },
]
