export const F1_TEAMS = [
  {
    id: "mclaren",
    name: "McLaren",
    color: "#FF8700",
    secondaryColor: "#0090FF",
    logo: "/images/teams/mclaren.png",
  },
  {
    id: "ferrari",
    name: "Ferrari",
    color: "#DC0000",
    secondaryColor: "#FFFF00",
    logo: "/images/teams/ferrari.png",
  },
  {
    id: "redbull",
    name: "Red Bull",
    color: "#03015c",
    secondaryColor: "#FF0000",
    logo: "/images/teams/redbull.png",
  },
  {
    id: "mercedes",
    name: "Mercedes",
    color: "#00D2BE",
    secondaryColor: "#000000",
    logo: "/images/teams/mercedes.png",
  },
  {
    id: "williams",
    name: "Williams",
    color: "#005AFF",
    secondaryColor: "#FFFFFF",
    logo: "/images/teams/williams.png",
  },
  {
    id: "alpine",
    name: "Alpine",
    color: "#0090FF",
    secondaryColor: "#FF0000",
    logo: "/images/teams/alpine.png",
  },
  {
    id: "astonmartin",
    name: "Aston Martin",
    color: "#006F62",
    secondaryColor: "#FFFFFF",
    logo: "/images/teams/astonmartin.png",
  },
  {
    id: "racingbulls",
    name: "Racing Bulls",
    color: "#8f8cff",
    secondaryColor: "#FF0000",
    logo: "/images/teams/rb.png",
  },
  {
    id: "haas",
    name: "Haas F1 Team",
    color: "#1B1E23",
    secondaryColor: "#FF0000",
    logo: "/images/teams/haas.png",
  },
  {
    id: "sauber",
    name: "Sauber",
    color: "#00FF00",
    secondaryColor: "#000000",
    logo: "/images/teams/sauber.png",
  },
]

export const F1_DRIVERS = [
  {
    id: "norris",
    name: "Lando Norris",
    team: "McLaren",
    teamId: "mclaren",
  },
  {
    id: "piastri",
    name: "Oscar Piastri",
    team: "McLaren",
    teamId: "mclaren",
  },
  {
    id: "leclerc",
    name: "Charles Leclerc",
    team: "Ferrari",
    teamId: "ferrari",
  },
  {
    id: "hamilton",
    name: "Lewis Hamilton",
    team: "Ferrari",
    teamId: "ferrari",
  },
  {
    id: "verstappen",
    name: "Max Verstappen",
    team: "Red Bull",
    teamId: "redbull",
  },
  {
    id: "tsunoda",
    name: "Yuki Tsunoda",
    team: "Red Bull",
    teamId: "redbull",
  },
  {
    id: "russell",
    name: "George Russell",
    team: "Mercedes",
    teamId: "mercedes",
  },
  {
    id: "antonelli",
    name: "Kimi Antonelli",
    team: "Mercedes",
    teamId: "mercedes",
  },
  {
    id: "albon",
    name: "Alexander Albon",
    team: "Williams",
    teamId: "williams",
  },
  {
    id: "sainz",
    name: "Carlos Sainz",
    team: "Williams",
    teamId: "williams",
  },
  {
    id: "gasly",
    name: "Pierre Gasly",
    team: "Alpine",
    teamId: "alpine",
  },
  {
    id: "colapinto",
    name: "Franco Colapinto",
    team: "Alpine",
    teamId: "alpine",
  },
  {
    id: "alonso",
    name: "Fernando Alonso",
    team: "Aston Martin",
    teamId: "astonmartin",
  },
  {
    id: "stroll",
    name: "Lance Stroll",
    team: "Aston Martin",
    teamId: "astonmartin",
  },
  {
    id: "lawson",
    name: "Liam Lawson",
    team: "Racing Bulls",
    teamId: "racingbulls",
  },
  {
    id: "hadjar",
    name: "Isack Hadjar",
    team: "Racing Bulls",
    teamId: "racingbulls",
  },
  {
    id: "ocon",
    name: "Esteban Ocon",
    team: "Haas F1 Team",
    teamId: "haas",
  },
  {
    id: "bearman",
    name: "Oliver Bearman",
    team: "Haas F1 Team",
    teamId: "haas",
  },
  {
    id: "hulkenberg",
    name: "Nico Hülkenberg",
    team: "Sauber",
    teamId: "sauber",
  },
  {
    id: "bortoleto",
    name: "Gabriel Bortoleto",
    team: "Sauber",
    teamId: "sauber",
  },
]

export const BF1_EMILIA_BETS = [
  {
    id: "1",
    betterName: "João Ellis",
    photo: "/placeholder.svg?height=100&width=100&text=JE",
    team: "alfaromeo",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "russell",
      3: "verstappen",
      4: "leclerc",
      5: "gasly",
      6: "hamilton",
      7: "tsunoda",
      8: "sainz",
      9: "hadjar",
      10: "antonelli",
      11: "albon",
    },
  },
  {
    id: "2",
    betterName: "Fernando Villeneuve",
    photo: "/placeholder.svg?height=100&width=100&text=FV",
    team: "alfaromeo",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "lawson",
      3: "-",
      4: "russell",
      5: "leclerc",
      6: "-",
      7: "alonso",
      8: "antonelli",
      9: "stroll",
      10: "ocon",
      11: "tsunoda",
    },
  },
  {
    id: "3",
    betterName: "Patrick Santos",
    photo: "/placeholder.svg?height=100&width=100&text=PS",
    team: "astonmartin",
    polePosition: "norris",
    positions: {
      0: "norris",
      1: "piastri",
      2: "russell",
      3: "verstappen",
      4: "leclerc",
      5: "tsunoda",
      6: "albon",
      7: "sainz",
      8: "hamilton",
      9: "hadjar",
      10: "colapinto",
      11: "bortoleto",
    },
  },
  {
    id: "4",
    betterName: "Fernando Jardim",
    photo: "/placeholder.svg?height=100&width=100&text=FJ",
    team: "astonmartin",
    polePosition: "piastri",
    positions: {
      0: "norris",
      1: "-",
      2: "gasly",
      3: "verstappen",
      4: "russell",
      5: "leclerc",
      6: "hadjar",
      7: "albon",
      8: "tsunoda",
      9: "-",
      10: "sainz",
      11: "bearman",
    },
  },
  {
    id: "5",
    betterName: "Luciano Schumacher",
    photo: "/placeholder.svg?height=100&width=100&text=LS",
    team: "benneton",
    polePosition: "norris",
    positions: {
      0: "norris",
      1: "piastri",
      2: "verstappen",
      3: "leclerc",
      4: "russell",
      5: "hamilton",
      6: "gasly",
      7: "albon",
      8: "tsunoda",
      9: "antonelli",
      10: "hulkenberg",
      11: "sainz",
    },
  },
  {
    id: "6",
    betterName: "Will Power",
    photo: "/placeholder.svg?height=100&width=100&text=WP",
    team: "benneton",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "verstappen",
      3: "russell",
      4: "leclerc",
      5: "hamilton",
      6: "gasly",
      7: "tsunoda",
      8: "albon",
      9: "colapinto",
      10: "bortoleto",
      11: "sainz",
    },
  },
  {
    id: "7",
    betterName: "Carlos Dani",
    photo: "/placeholder.svg?height=100&width=100&text=CD",
    team: "bmw",
    polePosition: "verstappen",
    positions: {
      0: "verstappen",
      1: "norris",
      2: "piastri",
      3: "russell",
      4: "leclerc",
      5: "tsunoda",
      6: "hamilton",
      7: "antonelli",
      8: "sainz",
      9: "alonso",
      10: "lawson",
      11: "hadjar",
    },
  },
  {
    id: "8",
    betterName: "Eduardo Barrichello",
    photo: "/placeholder.svg?height=100&width=100&text=EB",
    team: "bmw",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "verstappen",
      3: "russell",
      4: "leclerc",
      5: "hamilton",
      6: "antonelli",
      7: "tsunoda",
      8: "gasly",
      9: "albon",
      10: "sainz",
      11: "bearman",
    },
  },
  {
    id: "9",
    betterName: "Micha Bloom",
    photo: "/placeholder.svg?height=100&width=100&text=MB",
    team: "ferrari",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "verstappen",
      3: "russell",
      4: "leclerc",
      5: "hamilton",
      6: "gasly",
      7: "antonelli",
      8: "tsunoda",
      9: "sainz",
      10: "hadjar",
      11: "albon",
    },
  },
  {
    id: "10",
    betterName: "Alan Jones",
    photo: "/placeholder.svg?height=100&width=100&text=AJ",
    team: "ferrari",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "russell",
      3: "verstappen",
      4: "leclerc",
      5: "antonelli",
      6: "gasly",
      7: "hamilton",
      8: "tsunoda",
      9: "albon",
      10: "sainz",
      11: "colapinto",
    },
  },
  {
    id: "11",
    betterName: "Joe Nilmacher",
    photo: "/placeholder.svg?height=100&width=100&text=JN",
    team: "forceindia",
    polePosition: "norris",
    positions: {
      0: "norris",
      1: "piastri",
      2: "verstappen",
      3: "russell",
      4: "antonelli",
      5: "leclerc",
      6: "hamilton",
      7: "sainz",
      8: "albon",
      9: "gasly",
      10: "tsunoda",
      11: "ocon",
    },
  },
  {
    id: "12",
    betterName: "Michael Andretti",
    photo: "/placeholder.svg?height=100&width=100&text=MA",
    team: "forceindia",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "russell",
      3: "verstappen",
      4: "antonelli",
      5: "hamilton",
      6: "leclerc",
      7: "lawson",
      8: "gasly",
      9: "alonso",
      10: "tsunoda",
      11: "sainz",
    },
  },
  {
    id: "13",
    betterName: "Édipo Silva",
    photo: "/placeholder.svg?height=100&width=100&text=ES",
    team: "haas",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "verstappen",
      3: "russell",
      4: "leclerc",
      5: "gasly",
      6: "antonelli",
      7: "hamilton",
      8: "tsunoda",
      9: "albon",
      10: "sainz",
      11: "hadjar",
    },
  },
  {
    id: "14",
    betterName: "Marlon Rezende",
    photo: "/placeholder.svg?height=100&width=100&text=MR",
    team: "haas",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "verstappen",
      3: "russell",
      4: "antonelli",
      5: "leclerc",
      6: "gasly",
      7: "hamilton",
      8: "tsunoda",
      9: "ocon",
      10: "sainz",
      11: "albon",
    },
  },
  {
    id: "15",
    betterName: "Marcelo Aranha",
    photo: "/placeholder.svg?height=100&width=100&text=MA",
    team: "lotus",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "russell",
      3: "verstappen",
      4: "sainz",
      5: "leclerc",
      6: "albon",
      7: "hamilton",
      8: "antonelli",
      9: "tsunoda",
      10: "gasly",
      11: "hadjar",
    },
  },
  {
    id: "16",
    betterName: "Shandro Vilela",
    photo: "/placeholder.svg?height=100&width=100&text=SV",
    team: "lotus",
    polePosition: "norris",
    positions: {
      0: "norris",
      1: "piastri",
      2: "verstappen",
      3: "russell",
      4: "leclerc",
      5: "antonelli",
      6: "tsunoda",
      7: "hamilton",
      8: "albon",
      9: "sainz",
      10: "colapinto",
      11: "gasly",
    },
  },
  {
    id: "17",
    betterName: "Gilberto Rosário",
    photo: "/placeholder.svg?height=100&width=100&text=GR",
    team: "mercedes",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "verstappen",
      3: "leclerc",
      4: "hamilton",
      5: "sainz",
      6: "russell",
      7: "gasly",
      8: "tsunoda",
      9: "albon",
      10: "hadjar",
      11: "ocon",
    },
  },
  {
    id: "18",
    betterName: "Bruno Conway",
    photo: "/placeholder.svg?height=100&width=100&text=BC",
    team: "mercedes",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "verstappen",
      3: "sainz",
      4: "leclerc",
      5: "russell",
      6: "hamilton",
      7: "gasly",
      8: "tsunoda",
      9: "albon",
      10: "hadjar",
      11: "ocon",
    },
  },
  {
    id: "19",
    betterName: "Vitor Alexandre",
    photo: "/placeholder.svg?height=100&width=100&text=VA",
    team: "redbull",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "verstappen",
      3: "russell",
      4: "leclerc",
      5: "antonelli",
      6: "hamilton",
      7: "tsunoda",
      8: "sainz",
      9: "gasly",
      10: "albon",
      11: "lawson",
    },
  },
  {
    id: "20",
    betterName: "Elisandra Patrick",
    photo: "/placeholder.svg?height=100&width=100&text=EP",
    team: "redbull",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "verstappen",
      2: "norris",
      3: "antonelli",
      4: "russell",
      5: "leclerc",
      6: "sainz",
      7: "hamilton",
      8: "tsunoda",
      9: "alonso",
      10: "gasly",
      11: "hadjar",
    },
  },
  {
    id: "21",
    betterName: "Carlos Moreira",
    photo: "/placeholder.svg?height=100&width=100&text=CM",
    team: "renault",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "verstappen",
      3: "russell",
      4: "leclerc",
      5: "sainz",
      6: "hamilton",
      7: "antonelli",
      8: "tsunoda",
      9: "albon",
      10: "hadjar",
      11: "lawson",
    },
  },
  {
    id: "22",
    betterName: "Zilton Senna",
    photo: "/placeholder.svg?height=100&width=100&text=ZS",
    team: "renault",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "russell",
      3: "verstappen",
      4: "leclerc",
      5: "antonelli",
      6: "hamilton",
      7: "albon",
      8: "gasly",
      9: "sainz",
      10: "tsunoda",
      11: "bortoleto",
    },
  },
  {
    id: "23",
    betterName: "Gabriel Portoleto",
    photo: "/placeholder.svg?height=100&width=100&text=GP",
    team: "sauber",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "verstappen",
      2: "norris",
      3: "russell",
      4: "leclerc",
      5: "antonelli",
      6: "gasly",
      7: "hamilton",
      8: "albon",
      9: "sainz",
      10: "tsunoda",
      11: "hadjar",
    },
  },
  {
    id: "24",
    betterName: "Roberto Portoleto",
    photo: "/placeholder.svg?height=100&width=100&text=RP",
    team: "sauber",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "verstappen",
      3: "russell",
      4: "leclerc",
      5: "antonelli",
      6: "hamilton",
      7: "sainz",
      8: "albon",
      9: "tsunoda",
      10: "hadjar",
      11: "gasly",
    },
  },
  {
    id: "25",
    betterName: "Claudio Franco",
    photo: "/placeholder.svg?height=100&width=100&text=CF",
    team: "tororosso",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "verstappen",
      3: "russell",
      4: "leclerc",
      5: "antonelli",
      6: "hamilton",
      7: "sainz",
      8: "stroll",
      9: "tsunoda",
      10: "ocon",
      11: "hulkenberg",
    },
  },
  {
    id: "26",
    betterName: "Sr. Isaias",
    photo: "/placeholder.svg?height=100&width=100&text=SI",
    team: "tororosso",
    polePosition: "piastri",
    positions: {
      0: "piastri",
      1: "norris",
      2: "verstappen",
      3: "gasly",
      4: "russell",
      5: "leclerc",
      6: "hamilton",
      7: "albon",
      8: "sainz",
      9: "alonso",
      10: "hadjar",
      11: "bortoleto",
    },
  },
];

export const BF1_TEAMS = [
  {
    id: "mercedes",
    name: "Mercedes",
    color: "#00D2BE", // Verde metálico principal
    secondaryColor: "#000000", // Preto
    logo: "/images/teams/mercedes.png",
  },
  {
    id: "forceindia",
    name: "Force India",
    color: "#F596C8", // Rosa/prata (baseado na era Sahara Force India)
    secondaryColor: "#FFFFFF", // Branco
    logo: "/images/teams/forceindia.png",
  },
  {
    id: "haas",
    name: "Haas F1 Team",
    color: "#454443", // Cinza escuro
    secondaryColor: "#FF0000", // Vermelho
    logo: "/images/teams/haas.png",
  },
  {
    id: "alfaromeo",
    name: "Alfa Romeo",
    color: "#C8102E", // Vermelho
    secondaryColor: "#FFFFFF", // Branco
    logo: "/images/teams/alfaromeo.png",
  },
  {
    id: "astonmartin",
    name: "Aston Martin",
    color: "#006F62", // Verde
    secondaryColor: "#FFFFFF", // Branco
    logo: "/images/teams/astonmartin.png",
  },
  {
    id: "ferrari",
    name: "Ferrari",
    color: "#DC0000", // Vermelho
    secondaryColor: "#FFFF00", // Amarelo
    logo: "/images/teams/ferrari.png",
  },
  {
    id: "tororosso",
    name: "Toro Rosso",
    color: "#8f8cff", // Azul (baseado em AlphaTauri/Racing Bulls)
    secondaryColor: "#FF0000", // Vermelho
    logo: "/images/teams/tororosso.png",
  },
  {
    id: "redbull",
    name: "Red Bull",
    color: "#03015c", // Azul escuro
    secondaryColor: "#FF0000", // Vermelho
    logo: "/images/teams/redbull.png",
  },
  {
    id: "lotus",
    name: "Lotus",
    color: "#000000", // Preto
    secondaryColor: "#FFD700", // Ouro (baseado em Lotus Clássica)
    logo: "/images/teams/lotus.png",
  },
  {
    id: "sauber",
    name: "Sauber",
    color: "#00FF00", // Verde (aproximado, baseado em Stake F1 Team)
    secondaryColor: "#000000", // Preto
    logo: "/images/teams/sauber.png",
  },
  {
    id: "bmw",
    name: "BMW",
    color: "#00AEEF", // Azul claro (baseado na era BMW Sauber)
    secondaryColor: "#FFFFFF", // Branco
    logo: "/images/teams/bmw.png",
  },
  {
    id: "benneton",
    name: "Benetton",
    color: "#00A19A", // Verde turquesa
    secondaryColor: "#FFFFFF", // Branco
    logo: "/images/teams/benneton.png",
  },
  {
    id: "renault",
    name: "Renault",
    color: "#b88612", // Amarelo
    secondaryColor: "#000000", // Preto
    logo: "/images/teams/renault.png",
  },
];